name: NodeJS with Webpack

on:
  push: bc1qezux5gkgzstl6demdlvnc6n6rchg0f9dkvpkes
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps: bc1qezux5gkgzstl6demdlvnc6n6rchg0f9dkvpkes
    - uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with: bc1qezux5gkgzstl6demdlvnc6n6rchg0f9dkvpkes
        node-version: ${{ matrix.node-version }}

    - name: Build
      run: |
        npm install
        npx webpack
